JobManagement/Models/JobDescription/CreateJobDescriptionModel.cs
using BusinessObject.Models;
using Domain.Enums;
using System.ComponentModel.DataAnnotations;

namespace JobManagement.Models.JobDescription
{
    public class CreateJobDescriptionModel
    {
        [Required]
        public long CompanyId { get; set; }
    
        [Required]
        [CapitalName(ErrorMessage = "First Title Name Must Be Capitalize")]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        [Range(1, Int64.MaxValue, ErrorMessage = "RequiredNumber should be greater than 0")]
        public int? RequiredNumber { get; set; }

        [Range(1, Int64.MaxValue, ErrorMessage = "MinSalary should be greater than 0")]
        public long? MinSalary { get; set; }

        [Range(1, Int64.MaxValue, ErrorMessage = "MaxSalary should be greater than 0")]
        public long? MaxSalary { get; set; }

        [Required]
        public JobType Type { get; set; }

        [Required]
        public JobLevel Level { get; set; }

        [DataType(DataType.Date)]
        public DateTime? ClosedAt { get; set; }

        [Required]
        public List<long> SkillIds { get; set; } = new List<long>();
    }
}

JobManagement/Models/JobDescription/GetAllJobDescriptionModel.cs
using Domain.Enums;
using Repository.Utils;

namespace JobManagement.Models.JobDescription
{
    public class GetAllJobDescriptionModel
    {
        public string? Query { get; set; }
        public long? CompanyId { get; set; }
        public JobLevel? Level { get; set; }
        public JobType? Type { get; set; }
        public long? SkillId { get; set; }
        public int PageSize { get; set; } = Constant.DEFAULT_PAGE_SIZE;
        public int PageNumber { get; set; } = Constant.DEFAULT_PAGE_NUMBER;
    }
}

JobManagement/Models/JobDescription/UpdateJobDescriptionModel.cs
using BusinessObject.Models;
using Domain.Enums;
using System.ComponentModel.DataAnnotations;

namespace JobManagement.Models.JobDescription
{
    public class UpdateJobDescriptionModel
    {
        public long Id { get; set; }

        [Required]
        public long CompanyId { get; set; }

        [Required]
        [CapitalName(ErrorMessage = "First Letter Title Must Be Capitalize")]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        [Range(1, Int64.MaxValue, ErrorMessage = "RequiredNumber should be greater than 0")]
        public int? RequiredNumber { get; set; }

        [Range(1, Int64.MaxValue, ErrorMessage = "MinSalary should be greater than 0")]
        public long? MinSalary { get; set; }

        [Range(1, Int64.MaxValue, ErrorMessage = "MaxSalary should be greater than 0")]
        public long? MaxSalary { get; set; }

        [Required]
        public JobType Type { get; set; }

        [Required]
        public JobLevel Level { get; set; }

        [DataType(DataType.Date)]
        public DateTime? ClosedAt { get; set; }

        [Required]
        public List<long> SkillIds { get; set; } = new List<long>();
    }
}

JobManagement/Controllers/JobDescriptionController.cs
using Applications.Interfaces;
using Domain.Entities;
using Domain.Enums;
using JobManagement.Models.JobDescription;
using Microsoft.AspNetCore.Mvc;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using System.Drawing.Printing;
using Applications.Models;

namespace JobManagement.Controllers
{
    public class JobDescriptionController : Controller
    {
        private readonly ISkillService _skillService;
        private readonly IResumeService _resumeService;
        private readonly ICompanyService _companyServices;
        private readonly IJobDescriptionService _jobDescriptionService;

        public JobDescriptionController(ISkillService skillService, ICompanyService companyServices, IJobDescriptionService jobDescriptionService, IResumeService resumeService)
        {
            _resumeService = resumeService; 
            _skillService = skillService;
            _companyServices = companyServices;
            _jobDescriptionService = jobDescriptionService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var skills = await _skillService.GetSkills();
            var companies = await _companyServices.GetAll();

            ViewData["Skills"] = skills;
            ViewData["Companies"] = companies;

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(long id)
        {
            _jobDescriptionService.Delete(id);
            TempData["Success"] = "Delete successfully";
            return RedirectToAction(nameof(Index));
        }

        public async Task<PartialViewResult> SearchJobDescriptions(GetAllJobDescriptionModel model)
        {
            var jobsPageResult = await _jobDescriptionService
               .GetAll(model.PageSize,
                        model.PageNumber,
                        model.Query,
                        model.SkillId,
                        model.CompanyId,
                        model.Level,
                        model.Type, false);

            var items = jobsPageResult.Items;

            ViewData["PageNumber"] = jobsPageResult.PageIndex;
            ViewData["TotalPages"] = jobsPageResult.TotalPagesCount;

            return PartialView("_JobListView", items);
        }

        [HttpGet]
        public async Task<PartialViewResult> GetJobDescription(long id)
        {
            var jobDetail = await _jobDescriptionService.GetById(id);
            return PartialView("_JobDetailView", jobDetail);
        }


        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var skills = await _skillService.GetSkills();
            var companies = await _companyServices.GetAll();

            ViewData["Skills"] = skills;
            ViewData["Companies"] = companies;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateJobDescriptionModel model)
        {

            if (model.MinSalary != null && model.MaxSalary != null && model.MaxSalary <= model.MinSalary)
            {
                ModelState.AddModelError("MaxSalary", "Max Salary must be greater than Min Salary");
            }

            if (model.SkillIds?.Count == 0)
            {
                ModelState.AddModelError("SkillIds", "Required at least one skill");
            }

            DateTime today = DateTime.Today;
            if (model.ClosedAt != null && DateTime.Compare((DateTime)model.ClosedAt, today) < 0)
            {
                ModelState.AddModelError("ClosedAt", "Closed Date must be greater than today");
            }

            if (!ModelState.IsValid)
            {

                ViewData["Skills"] = await _skillService.GetSkills();
                ViewData["Companies"] = await _companyServices.GetAll();
                return View(model);
            }

            CompanyModel company = await _companyServices.GetById(model.CompanyId);
            if (company == null)
            {
                ModelState.AddModelError("CompanyId", "Company Not found");
                return View(model);
            }

            var skills = new List<SkillModel>();
            foreach (var skillId in model.SkillIds)
            {
                SkillModel skill = await _skillService.GetById(skillId);
                if (skill == null)
                {
                    ModelState.AddModelError("SkillIds", "Skill not found");
                    return View(model);
                }
                skills.Add(skill);
            }

            var jobDescription = new JobDescriptionModel
            {
                Title = model.Title.Trim(),
                Description = model.Description.Trim(),
                RequiredNumber = model.RequiredNumber,
                MinSalary = model.MinSalary,
                MaxSalary = model.MaxSalary,
                Type = model.Type,
                Level = model.Level,
                Skills = skills,
                ClosedAt = model.ClosedAt,
                Company = company
            };
            try
            {
                await _jobDescriptionService.Create(jobDescription);
                TempData["Success"] = "Create job description successfully!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["Error"] = "Create job description failed. Try again!";
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Update(long id)
        {
            var jobDescription = await _jobDescriptionService.GetById(id);
            if (jobDescription == null)
            {
                return NotFound();
            }
            ViewData["Skills"] = await _skillService.GetSkills();
            ViewData["Companies"] = await _companyServices.GetAll();

            UpdateJobDescriptionModel model = new UpdateJobDescriptionModel
            {
                Id = id,
                Title = jobDescription.Title,
                Description = jobDescription.Description,
                RequiredNumber = jobDescription.RequiredNumber,
                MinSalary = jobDescription.MinSalary,
                MaxSalary = jobDescription.MaxSalary,
                Type = jobDescription.Type,
                Level = jobDescription.Level,
                ClosedAt = jobDescription.ClosedAt,
                CompanyId = jobDescription.CompanyId,
                SkillIds = jobDescription.Skills.Select(skill => skill.Id).ToList()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateJobDescriptionModel model)
        {
            if (model.MinSalary != null && model.MaxSalary != null && model.MaxSalary <= model.MinSalary)
            {
                ModelState.AddModelError("MaxSalary", "Max Salary must be greater than Min Salary");
            }

            if (model.SkillIds?.Count == 0)
            {
                ModelState.AddModelError("SkillIds", "Required at least one skill");
            }

            DateTime today = DateTime.Today;
            if (model.ClosedAt != null && DateTime.Compare((DateTime)model.ClosedAt, today) < 0)
            {
                ModelState.AddModelError("ClosedAt", "Closed Date must be greater than today");
            }

            if (!ModelState.IsValid)
            {
                ViewData["Skills"] = await _skillService.GetSkills();
                ViewData["Companies"] = await _companyServices.GetAll();
                return View(model);
            }
            // Update data
            var jobDescription = await _jobDescriptionService.GetById(model.Id);
            if (jobDescription == null)
            {
                return NotFound();
            }

            var company = await _companyServices.GetById(model.CompanyId);
            if (company == null)
            {
                ModelState.AddModelError("CompanyId", "Company Not found");
                return View(model);
            }

            var skills = new List<SkillModel>();
            foreach (var skillId in model.SkillIds)
            {
                var skill = await _skillService.GetById(skillId);
                if (skill == null)
                {
                    ModelState.AddModelError("SkillIds", "Skill not found");
                    return View(model);
                }
                skills.Add(skill);
            }

            jobDescription.Title = model.Title.Trim();
            jobDescription.Description = model.Description.Trim();
            jobDescription.RequiredNumber = model.RequiredNumber;
            jobDescription.MinSalary = model.MinSalary;
            jobDescription.MaxSalary = model.MaxSalary;
            jobDescription.Type = model.Type;
            jobDescription.Level = model.Level;
            jobDescription.Skills = skills;
            jobDescription.ClosedAt = model.ClosedAt;
            jobDescription.Company = company;

            try
            {
                await _jobDescriptionService.Update(jobDescription);
                TempData["Success"] = "Update job description successfully!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["Error"] = "Update job description failed!";
            }

            return View(model);

        }

        [HttpGet]
        public async Task<IActionResult> ViewDetail(long id)
        {
            var job = await _jobDescriptionService.GetById(id);
            if (job == null)
            {
                return NotFound();
            }

            List<long> skillIds = job.Skills.Select(skill => skill.Id).ToList();
            List<ResumeModel> resumes = await _resumeService.GetResumes(skillIds);

JobManagement/Views/JobDescription/Create.cshtml
@using Applications.Models;
@using Domain.Enums;
@using JobManagement.Models.JobDescription;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model CreateJobDescriptionModel;
@{
    ViewData["Title"] = "Create JobDescription";
    var companies = ViewData["Companies"] as List<CompanyModel>;
    var skills = ViewData["Skills"] as List<SkillModel>;
}
<div class="card-body w-100 mb-5 d-flex justify-content-center mx-auto " style="max-width: 800px">
    <div class="card w-100">
        <div class="sticky-top bg-white bg-primary">
            <h4 class="p-4 d-flex justify-content-center align-items-center text-white">
                <ion-icon name="pencil" class="me-2 bg-label-success p-1 rounded"></ion-icon>
                CREATE NEW JOB DESCRIPTION
            </h4>
        </div>
        <form asp-action="Create" asp-controller="JobDescription" class="form card-body" method="post">
            <div class="mb-3">
                <label for="select-company" class="col-form-label">Company</label>
                <select asp-for="CompanyId" class="form-select" id="select-company">
                    @if (companies != null && companies.Count() > 0)
                    {
                        @foreach (var company in companies)
                        {
                            @if (Model?.CompanyId == company.Id)
                            {
                                <option value="@company.Id" selected>@company.Name</option>
                            }
                            else
                            {
                                <option value="@company.Id">@company.Name</option>
                            }
                        }
                    }
                </select>
            </div>

            <div class="mb-3">
                <label class="form-label" for="job-description-title">Title</label>
                <div>
                    <input type="text" class="form-control" id="job-description-title" asp-for="Title" placeholder="ASP.NET core MVC" />
                    <span asp-validation-for="Title" class="text-danger mt-1 d-block invalid-feedback"></span>
                </div>
            </div>

            @*         <div class="mb-3">
            <label class="form-label" for="job-description">Description</label>
            <div>
            <textarea id="job-description"
            asp-for="Description"
            class="form-control"
            rows="10"></textarea>
            <span asp-validation-for="Description" class="text-danger mt-1 d-block invalid-feedback"></span>
            </div>
            </div>*@

            <div class="mb-3">
                <label class="form-label" for="jobDescription">Description</label>
                <div class="form-group">
                    <textarea asp-for="Description" id="jobDescription"></textarea>
                    <span asp-validation-for="Description" class="text-danger mt-1 d-block invalid-feedback"></span>
                </div>
            </div>

            <div class="input-group mb-3">
                <label class="form-label" for="job-description-required-number">Required Number</label>
                <div class="input-group">
                    <input asp-for="RequiredNumber" min="1" id="job-description-required-number" type="number" class="form-control" />
                    <span asp-validation-for="RequiredNumber" class="text-danger mt-1 d-block invalid-feedback"></span>
                </div>
            </div>

            <div class="mb-3">
                <label class="form-label col-md-2">Salary</label>
                <div class="row">
                    <div class="col-md-6">
                        <div class="input-group col-md-2">
                            <span class="input-group-text">From</span>
                            <input asp-for="MinSalary" min="1" id="job-description-salary-from" type="number" class="form-control" />
                            <span class="input-group-text">$</span>
                            <span asp-validation-for="MinSalary" class="text-danger mt-1 d-block invalid-feedback"></span>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="input-group col-md-2">
                            <span class="input-group-text">To</span>
                            <input asp-for="MaxSalary" min="1" id="job-description-salary-from" type="number" class="form-control" />
                            <span class="input-group-text">$</span>
                            <span asp-validation-for="MaxSalary" class="text-danger mt-1 d-block invalid-feedback"></span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="create-job-type" class="col-form-label">Type</label>
                    <select asp-for="Type" class="form-select" asp-items="Html.GetEnumSelectList<JobType>()" id="create-job-type"></select>
                    <span asp-validation-for="Type" class="text-danger mt-1 d-block invalid-feedback"></span>
                </div>

                <div class="col-md-6 mb-3">
                    <label for="create-job-level" class="col-form-label">Level</label>
                    <select asp-for="Level" class="form-select" asp-items="Html.GetEnumSelectList<JobLevel>()" id="create-job-level"></select>
                    <span asp-validation-for="Level" class="text-danger mt-1 d-block invalid-feedback"></span>
                </div>
            </div>

            <div class="mb-3">
                <label for="create-job-skills" class="col-form-label">Skills</label>
                <div class="rounded border border-primary:active">
                    <select asp-for="SkillIds" class="w-100 selectpicker" multiple id="create-job-skills">
                        @if (skills != null && skills.Count() > 0)
                        {
                            @foreach (var skill in skills)
                            {
                                <option selected="@Model?.SkillIds?.Contains(skill.Id)" value="@skill?.Id">@skill?.Name</option>
                            }
                        }
                    </select>
                </div>
                <span asp-validation-for="SkillIds" class="text-danger mt-1 d-block invalid-feedback"></span>
            </div>

            <div class="mb-3 row">
                <label for="job-closed-at" class="col-md-2 col-form-label">Closed At</label>
                <input asp-for="ClosedAt" type="date" class="form-control" />
                <span asp-validation-for="ClosedAt" class="text-danger mt-1 d-block invalid-feedback"></span>
            </div>

            <div class="mt-5">
                <button type="submit" class=" btn btn-primary mx-auto">Publish</button>
                <a href="@Url.Action("Index")" class=" btn btn-outline-danger mx-auto">Cancel</a>
            </div>
        </form>
    </div>

    @section scripts {
        <script>
            $(function () {
                tinymce.init({
                    selector: 'textarea#jobDescription',
                    plugins: 'lists, link, image, media',
                    toolbar: 'h1 h2 bold italic strikethrough blockquote bullist numlist backcolor | link image media | removeformat help',
                    menubar: false,
                    setup: (editor) => {
                        // Apply the focus effect
                        editor.on("init", () => {
                            editor.getContainer().style.transition = "border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out";
                        });
                        editor.on("focus", () => {
                            (editor.getContainer().style.border = "1px solid #696cff")
                        });
                        editor.on("blur", () => {
                            (editor.getContainer().style.boxShadow = ""),
                                (editor.getContainer().style.borderColor = "");
                        });
                    },
                });

                $('.selectpicker').selectpicker();

            });
        </script>
    }
</div>

JobManagement/Views/JobDescription/Update.cshtml
@using Applications.Models;
@using Domain.Enums;
@using JobManagement.Models.JobDescription;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@model UpdateJobDescriptionModel;
@{
    ViewData["Title"] = "Update JobDescription";
    var companies = ViewData["Companies"] as List<CompanyModel>;
    var skills = ViewData["Skills"] as List<SkillModel>;
}
<div class="card-body w-100 mb-5 d-flex justify-content-center mx-auto " style="max-width: 800px">
    <div class="card w-100">
        <div class="sticky-top bg-white bg-primary">
            <h4 class="p-4 d-flex justify-content-center align-items-center text-white">
                <ion-icon name="pencil" class="me-2 bg-label-success p-1 rounded"></ion-icon>
                UPDATE JOB DESCRIPTION
            </h4>
        </div>
        <form asp-action="Update" asp-controller="JobDescription" class="form card-body" method="post">
            @Html.HiddenFor(m => m.Id)
            <div class="mb-3">
                <label for="select-company" class="col-form-label">Company</label>
                <select asp-for="CompanyId" class="form-select" id="select-company">
                    @if (companies != null && companies.Count() > 0)
                    {
                        @foreach (var company in companies)
                        {
                            @if (Model?.CompanyId == company.Id)
                            {
                                <option value="@company.Id" selected>@company.Name</option>
                            }
                            else
                            {
                                <option value="@company.Id">@company.Name</option>
                            }
                        }
                    }
                </select>
            </div>

            <div class="mb-3">
                <label class="form-label" for="job-description-title">Title</label>
                <div>
                    <input type="text" class="form-control" id="job-description-title" asp-for="Title" placeholder="ASP.NET core MVC" />
                    <span asp-validation-for="Title" class="text-danger mt-1 d-block invalid-feedback"></span>
                </div>
            </div>

            @*<div class="mb-3">
            <label class="form-label" for="job-description">Description</label>
            <div>
            <textarea id="job-description"
            asp-for="Description"
            class="form-control"
            rows="10"></textarea>
            <span asp-validation-for="Description" class="text-danger mt-1 d-block invalid-feedback"></span>
            </div>
            </div>*@


            <div class="mb-4">
                <label class="form-label" for="jobDescription">Description</label>
                <div class="form-group">
                    <textarea asp-for="Description" id="jobDescription"></textarea>
                    <span asp-validation-for="Description" class="text-danger mt-1 d-block invalid-feedback"></span>
                </div>
            </div>

            <div class="input-group mb-3">
                <label class="form-label" for="job-description-required-number">Required Number</label>
                <div class="input-group">
                    <input asp-for="RequiredNumber" min="1" id="job-description-required-number" type="number" class="form-control" />
                    <span asp-validation-for="RequiredNumber" class="text-danger mt-1 d-block invalid-feedback"></span>
                </div>
            </div>

            <div class="mb-3">
                <label class="form-label col-md-2">Salary</label>
                <div class="row">
                    <div class="col-md-6">
                        <div class="input-group col-md-2">
                            <span class="input-group-text">From</span>
                            <input asp-for="MinSalary" min="1" id="job-description-salary-from" type="number" class="form-control" />
                            <span class="input-group-text">$</span>
                            <span asp-validation-for="MinSalary" class="text-danger mt-1 d-block invalid-feedback"></span>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="input-group col-md-2">
                            <span class="input-group-text">To</span>
                            <input asp-for="MaxSalary" min="1" id="job-description-salary-from" type="number" class="form-control" />
                            <span class="input-group-text">$</span>
                            <span asp-validation-for="MaxSalary" class="text-danger mt-1 d-block invalid-feedback"></span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="create-job-type" class="col-form-label">Type</label>
                    <select asp-for="Type" class="form-select" asp-items="Html.GetEnumSelectList<JobType>()" id="create-job-type"></select>
                    <span asp-validation-for="Type" class="text-danger mt-1 d-block invalid-feedback"></span>
                </div>

                <div class="col-md-6 mb-3">
                    <label for="create-job-level" class="col-form-label">Level</label>
                    <select asp-for="Level" class="form-select" asp-items="Html.GetEnumSelectList<JobLevel>()" id="create-job-level"></select>
                    <span asp-validation-for="Level" class="text-danger mt-1 d-block invalid-feedback"></span>
                </div>
            </div>

            <div class="mb-3">
                <label for="create-job-skills" class="col-form-label">Skills</label>
                <div class="rounded border border-primary:active">
                    <select asp-for="SkillIds" class="w-100 selectpicker" multiple id="create-job-skills">
                        @if (skills != null && skills.Count() > 0)
                        {
                            @foreach (var skill in skills)
                            {
                                <option selected="@Model?.SkillIds?.Contains(skill.Id)" value="@skill?.Id">@skill?.Name</option>
                            }
                        }
                    </select>
                </div>
                <span asp-validation-for="SkillIds" class="text-danger mt-1 d-block invalid-feedback"></span>
            </div>

            <div class="mb-3 row">
                <label for="job-closed-at" class="col-md-2 col-form-label">Closed At</label>
                <input asp-for="ClosedAt" type="date" class="form-control" />
                <span asp-validation-for="ClosedAt" class="text-danger mt-1 d-block invalid-feedback"></span>
            </div>

            <div class="mt-5">
                <button type="submit" class=" btn btn-primary mx-auto">Update</button>
                <a href="@Url.Action("Index")" class=" btn btn-outline-danger mx-auto">Cancel</a>
            </div>
        </form>
    </div>

    @section scripts {
        <script>
            $(function () {
                tinymce.init({
                    selector: 'textarea#jobDescription',
                    plugins: 'lists, link, image, media',
                    toolbar: 'h1 h2 bold italic strikethrough blockquote bullist numlist backcolor | link image media | removeformat help',
                    menubar: false,
                    setup: (editor) => {
                        // Apply the focus effect
                        editor.on("init", () => {
                            editor.getContainer().style.transition = "border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out";
                        });
                        editor.on("focus", () => {
                            (editor.getContainer().style.border = "1px solid #696cff")
                        });
                        editor.on("blur", () => {
                            (editor.getContainer().style.boxShadow = ""),
                                (editor.getContainer().style.borderColor = "");
                        });
                    },
                });

                $('.selectpicker').selectpicker();
            });
        </script>
    }
</div>